### ISSUE TITLE
E2E tests fail in chapter 3.5 list view

### ISSUE THREAD

**Issue by happypork** [angularjs-de/dpunkt-buch-beispiele#4]
I followed the instructions in the book to chapter 3.5 Everything was OK until now.

All tests with following expression fail:

```
...expect(repeater(selector).column('book.title'))...
```

It seems like the result array is empty 

```
Chrome 41.0.2272 (Mac OS X 10.9.5) E2E: book list view should show the books in the proper order FAILED
    expect repeater 'table.bm-book-list tr' column 'book.title' toEqual ["CoffeeScript","JavaScript für Enterprise-Entwickler","Node.js & Co."]
    /Users/waldo/Documents/_Personal/bookmoney/test/e2e/templates/book_list.spec.js:44:35: expected ["CoffeeScript","JavaScript für Enterprise-Entwickler","Node.js & Co."] but was []
```

Any ideas? Thank you.

**Comment by sdogg81** [comment]
Hi there!

I'm having the same problem with the empty array. Tried everything I could find but still get the error message.

Any idea where this could come from? Here's a post of the test output:

Chromium 41.0.2272 (Ubuntu): Executed 1 of 7 SUCCESS (0 secs / 0.421 secs)
Chromium 41.0.2272 (Ubuntu) E2E: book list view should show the books in the pro
per order FAILED
        expect repeater 'table.bm-book-list tr' column 'book.title' toEqual ["CoffeeScript","JavaScript für Enterprise-Entwickler","Node.js & Co."]
        /home/stefan/PhpstormProjects/BookMonkeyProject/test/e2e/templates/book_list.spec.js:44:35: expected ["CoffeeScript","JavaScript für Enterprise-Entwickler","Node.js & Co."] but was []
Chromium 41.0.2272 (Ubuntu) E2E: book list view should show the correct book information FAILED
        expect repeater 'table.bm-book-list tr' row '0' toEqual ["CoffeeScript","Andreas Schubert","978-3-86490-050-1"]
        /home/stefan/PhpstormProjects/BookMonkeyProject/test/e2e/templates/book_list.spec.js:50:39: expected ["CoffeeScript","Andreas Schubert","978-3-86490-050-1"] but was []
Chromium 41.0.2272 (Ubuntu) E2E: book list view should allow filtering by book title FAILED
        expect repeater 'table.bm-book-list tr' column 'book.title' toEqual ["CoffeeScript"]
        /home/stefan/PhpstormProjects/BookMonkeyProject/test/e2e/templates/book_list.spec.js:66:32: expected ["CoffeeScript"] but was []
Chromium 41.0.2272 (Ubuntu) E2E: book list view should allow filtering by author FAILED
        expect repeater 'table.bm-book-list tr' column 'book.title' toEqual ["CoffeeScript"]
        /home/stefan/PhpstormProjects/BookMonkeyProject/test/e2e/templates/book_list.spec.js:75:32: expected ["CoffeeScript"] but was []
Chromium 41.0.2272 (Ubuntu) E2E: book list view should allow filtering by isbn FAILED
        expect repeater 'table.bm-book-list tr' column 'book.title' toEqual ["CoffeeScript"]
        /home/stefan/PhpstormProjects/BookMonkeyProject/test/e2e/templates/book_list.spec.js:84:32: expected ["CoffeeScript"] but was []

Thx

**Comment by justphil** [comment]
Thank you for your info. Will try to recreate the problem this week and will reply as soon as I find a solution.

Phil

**Comment by justphil** [comment]
Hi again,
just tried to recreate the problem on my machine. Short answer: Works on my machine. :-)

So, here is what I did. Maybe it'll help you to make the mentioned e2e test green. In case it doesn't, just let me know. So I'll try to help you.

Assumption:
- Chrome and Node.js (including NPM) have been installed.
- `http-server` NPM module has been installed globally via NPM. (`npm install -g http-server`)

Shell 1 (clone repo and run `http-server` on port 8080):

```
git clone git@github.com:angularjs-de/dpunkt-buch-beispiele.git
cd dpunkt-buch-beispiele/ch03_03_list_view/app
http-server
```

Shell 2 [install dev dependencies (karma, ng-scenario, etc.) and execute e2e tests]:

```
cd path/to/dpunkt-buch-beispiele/ch03_03_list_view
npm install
karma start karma-e2e.conf.js
```

I hope that you'll make it now! :-)

Further info:
Please note that meanwhile ng-scenario is considered deprecated when dealing with e2e tests. [Protractor](https://angular.github.io/protractor/#/) is your friend now.

Bye,
Phil
